id: web-client-demo
version: 1.0.0
type: application
dependencies:
  - id: am-lang-core
    realm: github
    type: git-repo
    tag: latest
    branch: master
    url: https://github.com/anderskjeldsen/am-lang-core.git
  - id: am-web-client
    type: local
    path: ../../
  - id: am-ssl
    type: local
    path: ../../../am-ssl
platforms:
  - id: libc
    abstract: true
  - id: amigaos
    extends: libc
    gccCommand: m68k-amigaos-gcc -O3
    asmCommand: vasmm68k_mot
    additionalHeaders:
    additionalAsmSources:
    additionalCSources: 
    additionalIncludePaths:
    gccAdditionalOptions:
      - -noixemul     
    gccAdditionalLibraries:
      - socket
      - amisslstubs
      - amisslauto
  - id: macos
    extends: libc
    gccCommand: gcc -O3
    additionalHeaders:
    additionalAsmSources:
    additionalCSources: 
    additionalIncludePaths:
    gccAdditionalOptions:
    gccAdditionalLibraries:
  - id: macos-arm
    extends: libc
    gccCommand: gcc -O3
    additionalHeaders:
    additionalAsmSources:
    additionalCSources: 
    additionalIncludePaths:
      - /opt/homebrew/opt/openssl/include
    gccLibraryPaths:
      - /opt/homebrew/opt/openssl/lib
    gccAdditionalLibraries:
      - ssl
      - crypto

#    additionalIncludePaths:
#    gccAdditionalOptions:
#    gccAdditionalLibraries:
  - id: linux-x64
    extends: libc
    gccCommand: gcc -O3
    additionalHeaders:
    additionalAsmSources:
    additionalCSources: 
    additionalIncludePaths:
    gccAdditionalOptions:
    gccAdditionalLibraries:

buildTargets:
  - id: amigaos_docker
    platform: amigaos
    dockerBuild:
      image: amiga-gcc
      buildPath: /host
  - id: macos
    platform: macos
  - id: macos-arm
    platform: macos-arm
  - id: linux-x64
    platform: linux-x64